services:
  league-tracker:
    build: .
    container_name: league-tracker
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
